Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2020-01, with the labels that each got.

#20 Update README.md: more prominent Help Wanted
  README.md
Labels: 3: Reviews Complete

#19 [MM-19897] Improvements for `/msoffice createevent` and `/msoffice findmeetings`
  server/api/api.go
  server/api/calendar.go
  server/plugin/command/command.go
  server/plugin/command/create_event.go
  server/plugin/command/find_meeting_times.go
  server/plugin/command/help.go
  server/remote/event.go
  server/remote/meeting.go
  server/remote/msgraph/find_meeting_times.go
Labels: 3: Reviews Complete

#18 [MM-19893] Outlook user status sync intial implementation
  Makefile
  assets/profile.png
  go.mod
  go.sum
  plugin.json
  server/api/api.go
  server/api/availability.go
  server/api/availability_test.go
  server/api/mock_api/mock_availability.go
  server/api/mock_api/mock_calendar.go
  server/api/notification.go
  server/api/oauth2.go
  server/api/plugin_api.go
  server/api/status_sync_job.go
  server/config/config.go
  server/plugin/command/availability.go
  server/plugin/command/command.go
  server/plugin/plugin.go
  server/remote/client.go
  server/remote/common.go
  server/remote/mock_remote/mock_client.go
  server/remote/mock_remote/mock_remote.go
  server/remote/msgraph/batch_request.go
  server/remote/msgraph/call.go
  server/remote/msgraph/get_me.go
  server/remote/msgraph/get_notification_data.go
  server/remote/msgraph/get_schedule_batched.go
  server/remote/msgraph/get_schedule_batched_test.go
  server/remote/msgraph/get_super_user_token.go
  server/remote/msgraph/remote.go
  server/remote/remote.go
  server/remote/schedule.go
  server/remote/user.go
  server/store/mock_store/mock_event_store.go
  server/store/mock_store/mock_user_store.go
  server/store/store.go
  server/store/user_store.go
  server/testdata/batch_requests.json
  server/testdata/get_me_response.json
  server/testdata/get_schedule_response_batch.json
  server/testdata/get_schedule_response_busy.json
  server/testdata/get_schedule_response_free.json
  server/testdata/get_schedule_response_invalid_email.json
  server/testdata/webhook_event_ notification.json
  server/utils/bot/mock_bot/mock_logger.go
  server/utils/plugin_api/mock_plugin_api/mock_plugin_api.go
  server/utils/plugin_api/plugin_api.go
Labels: 3: Reviews Complete

#23 Change bot name
  server/config/const.go
Labels: 3: Reviews Complete

#26 [MM-21691] Handle errors for getSchedule call
  server/remote/msgraph/get_schedule_batched.go
Labels: 2: Dev Review, 3: Reviews Complete

#25 [MM-21689] Handle timezone complications between Go and Microsoft Graph
  go.sum
  server/api/api.go
  server/api/availability.go
  server/api/calendar.go
  server/api/event.go
  server/api/mock_api/mock_calendar.go
  server/api/status_sync_job.go
  server/api/user.go
  server/plugin/command/create_event.go
  server/plugin/command/find_meeting_times.go
  server/plugin/command/get_calendars.go
  server/plugin/command/view_calendar.go
  server/plugin/plugin.go
  server/remote/client.go
  server/remote/common_test.go
  server/remote/date_time.go
  server/remote/date_time_test.go
  server/remote/mock_remote/mock_client.go
  server/remote/msgraph/get_schedule_batched_test.go
  server/remote/msgraph/get_user_mailbox_settings.go
  server/remote/user.go
  server/testdata/get_mainbox_settings_response.json
  server/testdata/get_schedule_response_busy.json
  server/utils/tz/conversion.go
  server/utils/tz/data.go
  server/utils/tz/tz_test.go
Labels: 2: Dev Review, 2: QA Review
