Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2020-03, with the labels that each got.

#38 Fix findmeetings typo
  server/command/command.go
Labels: 2: QA Review

#43 [MM-22787] Convert status sync job to use cluster job API
  Makefile
  go.mod
  go.sum
  server/jobs/job_manager.go
  server/jobs/job_manager_test.go
  server/jobs/mock_cluster/mock_cluster.go
  server/jobs/status_sync_job.go
  server/mscalendar/status_sync_job.go
  server/plugin/plugin.go
Labels: 2: QA Review

#46 [MM-22425] add permissions and bot account instructions to README
  README.md
Labels: 3: Reviews Complete

#40 Add ClientState and tests
  server/mscalendar/notification.go
  server/mscalendar/notification_test.go
  server/remote/msgraph/subscription.go
Labels: 3: Reviews Complete, QA Review Done

#36 [MM-21140] Daily summary job
  go.mod
  go.sum
  plugin.json
  server/command/command.go
  server/command/daily_summary.go
  server/command/view_calendar.go
  server/config/config.go
  server/jobs/job_manager.go
  server/mscalendar/calendar.go
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_job.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/filters.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/mscalendar.go
  server/mscalendar/user.go
  server/mscalendar/views/calendar.go
  server/plugin/plugin.go
  server/store/daily_summary_store.go
  server/store/mock_store/mock_store.go
  server/store/store.go
Labels: 3: Reviews Complete, QA Review Done

#63 Fix build
  server/utils/httputils/utils_test.go
  webapp/package-lock.json
Labels: 3: Reviews Complete

#42 Delete subscription upon disconnecting user
  server/mscalendar/user.go
Labels: 3: Reviews Complete, Lifecycle/1:stale, QA Review Done
