Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2020-05, with the labels that each got.

#73 Add status change confirmation
  server/api/api.go
  server/api/post_action.go
  server/command/availability.go
  server/command/connect_test.go
  server/command/disconnect_test.go
  server/config/config.go
  server/config/const.go
  server/jobs/job_manager_test.go
  server/jobs/status_sync_job.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/filters.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/mscalendar.go
  server/mscalendar/notification_test.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/settings.go
  server/mscalendar/user.go
  server/mscalendar/views/calendar.go
  server/mscalendar/views/status_change_notification.go
  server/plugin/plugin.go
  server/remote/calendar.go
  server/remote/msgraph/get_default_calendar_view.go
  server/remote/schedule.go
  server/store/mock_store/mock_store.go
  server/store/setting_store.go
  server/store/user_store.go
  server/testdata/get_calendar_view_response.json
  server/utils/pluginapi/api.go
  server/utils/settingspanel/handler.go
Labels: 4: Reviews Complete, QA Review Done

#107 Add image for granting admin consent
  README.md
Labels: 4: Reviews Complete, QA Review Done

#102 Improve notification looks
  server/mscalendar/notification.go
Labels: 4: Reviews Complete

#106 Various improvements over commands
  server/command/availability.go
  server/command/command.go
  server/command/disconnect_test.go
  server/command/help.go
  server/command/subscribe.go
  server/command/unsubscribe.go
Labels: 4: Reviews Complete, QA Review Done

#83 use StoreTTL in place of Store for managing OAuth2 state
  server/store/oauth2_store.go
Labels: 4: Reviews Complete, QA Review Done

#101 Use appropriate log levels, wrap errors coming from msgraph for logging
  server/api/post_action.go
  server/command/command.go
  server/command/create_event.go
  server/jobs/daily_summary_job.go
  server/jobs/job_manager.go
  server/jobs/renew_job.go
  server/jobs/status_sync_job.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/daily_summary.go
  server/mscalendar/notification.go
  server/mscalendar/oauth2.go
  server/mscalendar/settings.go
  server/mscalendar/settings_daily_summary.go
  server/mscalendar/user.go
  server/mscalendar/welcomer.go
  server/plugin/plugin.go
  server/remote/msgraph/create_calendar.go
  server/remote/msgraph/create_event.go
  server/remote/msgraph/delete_calendar.go
  server/remote/msgraph/event.go
  server/remote/msgraph/find_meeting_times.go
  server/remote/msgraph/get_calendars.go
  server/remote/msgraph/get_default_calendar_view.go
  server/remote/msgraph/get_mailbox_settings.go
  server/remote/msgraph/get_me.go
  server/remote/msgraph/get_notification_data.go
  server/remote/msgraph/get_schedule_batched.go
  server/remote/msgraph/get_super_user_token.go
  server/remote/msgraph/subscription.go
  server/store/subscription_store.go
  server/utils/httputils/utils.go
  server/utils/settingspanel/settings.go
Labels: 4: Reviews Complete, AutoMerge

#122 Remove references to "common"
  plugin.json
Labels: 4: Reviews Complete

#132 Use timezone when displaying event details
  server/mscalendar/notification.go
  server/mscalendar/notification_test.go
  server/mscalendar/views/calendar.go
Labels: 4: Reviews Complete

#118 [GH-89] Allow status change to support DND and Away
  server/mscalendar/availability.go
  server/mscalendar/settings.go
  server/mscalendar/welcome_flow.go
  server/store/flow_store.go
  server/store/setting_store.go
  server/store/user_store.go
Labels: 4: Reviews Complete

#139 [GH-127] Replace the `0` with `12` to indicate noon and midnight
  server/mscalendar/settings_daily_summary.go
Labels: 4: Reviews Complete

#141 Remove daily summary index
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/oauth2.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/user.go
  server/store/daily_summary_store.go
  server/store/mock_store/mock_store.go
  server/store/setting_store.go
  server/store/store.go
  server/store/user_store.go
Labels: 4: Reviews Complete

#146 add release, and HW badges
  README.md
Labels: 2: Dev Review

#117 [GH87] Add "receive reminder" setting to login flow
  server/mscalendar/welcome_flow.go
  server/store/flow_store.go
Labels: 4: Reviews Complete

#120 [GH-103] Add event reminder subscriptions to settings panel
  server/mscalendar/settings.go
  server/mscalendar/settings_notifications.go
  server/plugin/plugin.go
Labels: 4: Reviews Complete

#138 [GH-129] MS Graph error is shown when selecting acceptance
  server/api/post_action.go
Labels: 4: Reviews Complete

#143 [GH-14] Add at-rest encryption for OAuth2 token
  README.md
  plugin.json
  server/config/config.go
  server/mscalendar/client.go
  server/mscalendar/notification.go
  server/mscalendar/notification_test.go
  server/mscalendar/oauth2.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/user.go
  server/plugin/plugin.go
  server/utils/encryption.go
Labels: 4: Reviews Complete

#145 Remove job configs
  plugin.json
  server/jobs/daily_summary_job.go
  server/jobs/job_manager.go
  server/jobs/job_manager_test.go
  server/jobs/status_sync_job.go
  server/plugin/plugin.go
Labels: 1: PM Review, 3: QA Review
