Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2020-04, with the labels that each got.

#59 Use KVSetWithOptions with Atomic: true
  server/command/daily_summary.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/client.go
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/filters.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/oauth2.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/user.go
  server/store/daily_summary_store.go
  server/store/mock_store/mock_store.go
  server/store/user_store.go
  server/utils/kvstore/hashed_key.go
  server/utils/kvstore/kvstore.go
  server/utils/kvstore/plugin_store.go
Labels: AutoMerge

#52 Handle case where mail is nil
  server/remote/msgraph/get_me.go
Labels: QA Review Done

#78 Use correct prefix for OAuth2 store keys
  server/store/oauth2_store.go
Labels: 3: Reviews Complete

#74 Use cluster.Job for daily summary job
  plugin.json
  server/jobs/daily_summary_job.go
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_job.go
  server/plugin/plugin.go
Labels: 3: Reviews Complete, QA Review Done

#80 Define maintainer
  CODEOWNERS
  README.md
Labels: 3: Reviews Complete

#72 Use batch requests for daily summary job
  go.mod
  go.sum
  server/command/daily_summary.go
  server/jobs/daily_summary_job.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/calendar.go
  server/mscalendar/daily_summary.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/views/calendar.go
  server/remote/calendar.go
  server/remote/client.go
  server/remote/mock_remote/mock_client.go
  server/remote/msgraph/get_default_calendar_view.go
  server/remote/msgraph/get_schedule_batched.go
  server/remote/remote.go
  server/store/daily_summary_store.go
  server/utils/tz/conversion.go
Labels: 3: Reviews Complete, QA Review Done

#81 Notification processor fixes
  server/api/notification.go
  server/mscalendar/notification.go
  server/mscalendar/notification_test.go
Labels: 3: Reviews Complete

#76 Remove dedicated Microsoft integration user
  README.md
  server/command/command.go
  server/command/connect.go
  server/command/connect_test.go
  server/command/disconnect.go
  server/command/disconnect_test.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/client.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/filters.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/oauth2.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/user.go
  server/remote/client.go
  server/remote/mock_remote/mock_client.go
  server/remote/mock_remote/mock_remote.go
  server/remote/msgraph/get_schedule_batched.go
  server/remote/msgraph/get_schedule_batched_test.go
  server/remote/msgraph/remote.go
  server/remote/remote.go
  server/remote/schedule.go
  server/utils/oauth2connect/oauth2.go
  server/utils/oauth2connect/oauth2_connect.go
Labels: 3: Reviews Complete, QA Review Done

#79 [GH-53] Accept or decline meetings from the notification message
  server/api/post_action.go
  server/mscalendar/mock_plugin_api/mock_plugin_api.go
  server/mscalendar/mscalendar.go
  server/mscalendar/notification.go
  server/mscalendar/notification_test.go
  server/remote/event.go
  server/store/event_store.go
  server/utils/pluginapi/api.go
  server/utils/slack_attachments.go
Labels: 3: Reviews Complete, QA Review Done

#90 Drop second maintainer from CODEOWNERS
  CODEOWNERS
Labels: 3: Reviews Complete

#85 Fix logging calls
  server/jobs/daily_summary_job.go
  server/jobs/job_manager.go
  server/jobs/status_sync_job.go
  server/mscalendar/daily_summary.go
  server/mscalendar/user.go
  server/plugin/plugin.go
Labels: 3: Reviews Complete

#105 [GH104] Check when the error when cleaning a setting post is not found
  server/mscalendar/settings.go
  server/utils/settingspanel/settings.go
Labels: 2: QA Review

#44 Login workflow
  Makefile
  server/command/availability.go
  server/command/command.go
  server/command/connect.go
  server/command/connect_test.go
  server/command/create_calendar.go
  server/command/create_event.go
  server/command/daily_summary.go
  server/command/delete_calendar.go
  server/command/disconnect.go
  server/command/disconnect_test.go
  server/command/find_meeting_times.go
  server/command/get_calendars.go
  server/command/help.go
  server/command/info.go
  server/command/settings.go
  server/command/subscribe.go
  server/command/view_calendar.go
  server/mscalendar/availability.go
  server/mscalendar/availability_test.go
  server/mscalendar/calendar.go
  server/mscalendar/daily_summary_test.go
  server/mscalendar/mock_mscalendar/mock_mscalendar.go
  server/mscalendar/mock_welcomer/mock_welcomer.go
  server/mscalendar/mscalendar.go
  server/mscalendar/oauth2.go
  server/mscalendar/oauth2_test.go
  server/mscalendar/user.go
  server/mscalendar/welcome_flow.go
  server/mscalendar/welcomer.go
  server/plugin/plugin.go
  server/store/flow_store.go
  server/store/mock_store/mock_store.go
  server/store/store.go
  server/store/user_store.go
  server/store/welcome_store.go
  server/utils/bot/bot.go
  server/utils/bot/flow_controller.go
  server/utils/bot/mock_bot/mock_poster.go
  server/utils/bot/poster.go
  server/utils/flow/empty_step.go
  server/utils/flow/flow.go
  server/utils/flow/handler.go
  server/utils/settingspanel/handler.go
Labels: 3: Reviews Complete, QA Review Done
