Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2024-08, with the labels that each got.

#383 Replace hard coded HTTP verb strings with net/http constants
  calendar/api/api.go
Labels: AutoMerge

#385 [GH-367] Remove "prompt" param from auth code URL
  calendar/engine/oauth2.go
  calendar/engine/oauth2_test.go
Labels: 4: Reviews Complete

#386 [MM-60003] Add path escaping to "OAuth2Authority"
  msgraph/get_super_user_token.go
Labels: 3: Security Review

#387 [MM-60021] Adding error logging
  calendar/api/autocomplete.go
  calendar/api/connected_user.go
  calendar/api/events.go
  calendar/api/notification.go
  calendar/plugin/plugin.go
Labels: 4: Reviews Complete

#397 [GH-394] Add timeout to http client
  msgraph/remote.go
Labels: 4: Reviews Complete

#401 [MM-60204] Added logic to sanitize the validation token for webhook requests
  go.mod
  go.sum
  msgraph/handle_webhook.go
Labels: 3: QA Review

#406 Bump plugin version to v1.3.2
  README.md
  plugin.json
Labels: 4: Reviews Complete

#408 Bump version to 1.3.4
  plugin.json
Labels: 4: Reviews Complete
