Repository mattermost/mattermost-plugin-mscalendar, pull requests merged in 2025-05, with the labels that each got.

#452 Upgrade node version to 20.11
  .nvmrc
Labels: 2: Dev Review

#445 [MM-63254] Add diagnostics data to the Support Packet
  calendar/config/config.go
  calendar/engine/calendar_test.go
  calendar/engine/event_responder_test.go
  calendar/engine/mscalendar_test.go
  calendar/engine/oauth2_test.go
  calendar/engine/subscription_test.go
  calendar/engine/user_test.go
  calendar/plugin/support_packet.go
  calendar/remote/mock_remote/mock_remote.go
  calendar/store/mock_store/mock_store.go
  calendar/store/subscription_store.go
  calendar/store/subscription_store_test.go
  calendar/store/user_store.go
  calendar/store/user_store_test.go
  calendar/testutil/mock_setup.go
  calendar/utils/kvstore/crypt.go
  calendar/utils/kvstore/hashed_key.go
  calendar/utils/kvstore/hashed_key_test.go
  calendar/utils/kvstore/kvstore.go
  calendar/utils/kvstore/plugin_store.go
  calendar/utils/kvstore/plugin_store_test.go
  go.mod
  go.sum
Labels: 3: QA Review

#454 Added cache store for settings panel and welcome index
  calendar/store/store.go
  calendar/utils/flow/handler.go
  calendar/utils/kvstore/cache.go
  calendar/utils/kvstore/cache_store_test.go
  calendar/utils/kvstore/hashed_key_test.go
  calendar/utils/settingspanel/handler.go
Labels: 4: Reviews Complete
